services:
  mysql:
    image: mysql:8.0
    container_name: attendance_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: narnika_employee
      MYSQL_ROOT_PASSWORD: 843314
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: attendance_backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      SPRING_PROFILES_ACTIVE: mysql
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/narnika_employee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 843314
      APP_ADMIN_USERNAME: narnika
      APP_ADMIN_PASSWORD: fahim620
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    container_name: attendance_frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  mysql_data:
