server.port=8080
spring.application.name=attendance-system

# Default production database (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/narnika_employee?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=843314

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

app.jwt.secret=superSecureJwtSecretKeyForAttendanceSystem2026AttendanceSystem
app.jwt.expiration-ms=86400000
app.admin.username=narnika
app.admin.password=fahim620

spring.jackson.serialization.write-dates-as-timestamps=false
